### PR TITLE
Use Vite to build MeshMap

### PR DESCRIPTION
**Pull request by USA-RedDragon**

### CODE REVIEW

**Comment by USA-RedDragon** [comment]
@kn6plv, if you want a live preview of these changes, I have this branch deployed at https://meshmap.aredn.mcswain.dev/

**Comment by aanon4** [comment]
I finally had a moment to look at this, but it requires a version of Node that's not available on Bullseye by default.

**Comment by USA-RedDragon** [comment]
Oh, the [Debian packaged NodeJS version](https://packages.debian.org/search?keywords=nodejs&searchon=names&exact=1&suite=all&section=all) v12 is quite old (in NodeJS terms) and no longer in support by NodeJS with it's last supported release being in 2022: https://nodejs.org/en/about/previous-releases

image

I've personally used `nvm` to manage my NodeJS versions on my devbox for the last 6 years or so, it's pretty no-frills: https://github.com/nvm-sh/nvm

I should note that at this point I also have this branch that has all of the dependencies up to date (and gets automatic PRs to do so with Renovate), though some of that is me adding a mesh walker script in python and a few tweaks that don't belong upstream: https://github.com/kn6plv/MeshMap/compare/main...USA-RedDragon:MeshMap:k8s

**Comment by aanon4** [comment]
Oh yes, it's horrendously out of date I know, but I'd still rather not pull in an external dependency if I can avoid it.

**Pull request closed without merging**
